# Nacos配置中心配置
nacos:
  config:
    server-addr: 192.168.0.120:8848
    data-id: dubbo-consumer
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
      log-enable: true
    type: yaml
    namespace: public
    auto-refresh: true







